---
- name: Day1 OS Provision
  hosts: localhost
  vars:
    primary_host_ip: "{{ primary_host_ip }}"
    cloud_platform_manager_ip: "{{ cloud_platform_manager_ip }}"
    day1_json_file: "{{ day1_json_file }}"
  tasks:
    - name: Install Azure Stack HCI OS on specified nodes
      dellemc.apexcp_azure.dell_apexcp_azure_system_os_provision:
        primary_host_ip: "{{ primary_host_ip }}"
        cloud_platform_manager_ip: "{{ cloud_platform_manager_ip }}"
        day1_json_file: "{{ day1_json_file }}"
      async: 7200
      poll: 0
      register: os_provision_status
    - name: Check if OS provision job is completed...The OS provision is still ongoing
      async_status:
        jid: "{{ os_provision_status.ansible_job_id }}"
      register: job_result
      until: job_result.finished
      retries: 120
      delay: 60
    - name: Get OS provision result
      debug:
        msg:
        - "changed: {{job_result['changed']}}"
        - "failed: {{job_result['failed']}}"
        - "msg: {{job_result['msg']}}"
        - "os_installation: {{job_result['os_provision_result']}}"
